export default [
  {
    id: 1,
    name: 'Beauty fly',
    price: 100,
    image: require('../../../assets/images/Products-images/Beatyfly.jpeg'),
    author: 'Wowgirl',
    authorpic: require('../../../assets/images/Author-images/WowgirlAuth.jpeg'),
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque ipsum rem provident sapiente cum, nemo id quia maiores eum tenetur nostrum. Autem sapiente voluptatibus blanditiis nulla hic dolor, in dignissimos.',
    category: 'Painting',
    time: '2 days ago',
  },
  {
    id: 2,
    name: 'BlackStar',
    price: 25,
    image: require('../../../assets/images/Products-images/blackstar.jpeg'),
    author: 'Nyd',
    authorpic: require('../../../assets/images/Author-images/me.jpeg'),
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque ipsum rem provident sapiente cum, nemo id quia maiores eum tenetur nostrum. Autem sapiente voluptatibus blanditiis nulla hic dolor, in dignissimos.',
    category: 'Manga',
    time: '2 days ago',
  },
  {
    id: 3,
    name: 'Browse',
    price: 10,
    image: require('../../../assets/images/Products-images/Browse.jpeg'),
    author: 'Habibi',
    authorpic: require('../../../assets/images/Author-images/HabibiAuth.jpeg'),
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque ipsum rem provident sapiente cum, nemo id quia maiores eum tenetur nostrum. Autem sapiente voluptatibus blanditiis nulla hic dolor, in dignissimos.',
    category: 'Calligraphy',
    time: '2 days ago',
  },
  {
    id: 4,
    name: 'CrazyMan',
    price: 10,
    image: require('../../../assets/images/Products-images/CrazyMan.webp'),
    author: 'Habibi',
    authorpic: require('../../../assets/images/Author-images/HabibiAuth.jpeg'),
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque ipsum rem provident sapiente cum, nemo id quia maiores eum tenetur nostrum. Autem sapiente voluptatibus blanditiis nulla hic dolor, in dignissimos.',
    category: 'Digital Painting',
    time: '2 days ago',
  },
  {
    id: 5,
    name: 'Cringe',
    price: 105,
    image: require('../../../assets/images/Products-images/Cringe.jpeg'),
    author: 'Wowgirl',
    authorpic: require('../../../assets/images/Author-images/WowgirlAuth.jpeg'),
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque ipsum rem provident sapiente cum, nemo id quia maiores eum tenetur nostrum. Autem sapiente voluptatibus blanditiis nulla hic dolor, in dignissimos.',
    category: 'Illustration',
    time: '2 days ago',
  },
  {
    id: 6,
    name: 'Elephant',
    price: 200,
    image: require('../../../assets/images/Products-images/Elephant.jpeg'),
    author: 'Habibi',
    authorpic: require('../../../assets/images/Author-images/HabibiAuth.jpeg'),
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque ipsum rem provident sapiente cum, nemo id quia maiores eum tenetur nostrum. Autem sapiente voluptatibus blanditiis nulla hic dolor, in dignissimos.',
    category: 'Scuplture',
    time: '2 days ago',
  },
  {
    id: 7,
    name: 'Escanor',
    price: 100,
    image: require('../../../assets/images/Products-images/Escanor.jpeg'),
    author: 'Nyd',
    authorpic: require('../../../assets/images/Author-images/me.jpeg'),
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque ipsum rem provident sapiente cum, nemo id quia maiores eum tenetur nostrum. Autem sapiente voluptatibus blanditiis nulla hic dolor, in dignissimos.',
    category: 'Manga',
    time: '2 days ago',
  },
  {
    id: 8,
    name: 'Exhausted',
    price: 250,
    image: require('../../../assets/images/Products-images/Exhausted.jpeg'),
    author: 'Wowgirl',
    authorpic: require('../../../assets/images/Author-images/WowgirlAuth.jpeg'),
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque ipsum rem provident sapiente cum, nemo id quia maiores eum tenetur nostrum. Autem sapiente voluptatibus blanditiis nulla hic dolor, in dignissimos.',
    category: 'Painting',
    time: '2 days ago',
  },
  {
    id: 9,
    name: 'Fade',
    price: 100,
    image: require('../../../assets/images/Products-images/Fade.jpeg'),
    author: 'Wowgirl',
    authorpic: require('../../../assets/images/Author-images/WowgirlAuth.jpeg'),
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque ipsum rem provident sapiente cum, nemo id quia maiores eum tenetur nostrum. Autem sapiente voluptatibus blanditiis nulla hic dolor, in dignissimos.',
    category: 'Photography',
    time: '2 days ago',
  },
  {
    id: 10,
    name: 'Feture',
    price: 100,
    image: require('../../../assets/images/Products-images/Feture.jpeg'),
    author: 'Habibi',
    authorpic: require('../../../assets/images/Author-images/HabibiAuth.jpeg'),
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque ipsum rem provident sapiente cum, nemo id quia maiores eum tenetur nostrum. Autem sapiente voluptatibus blanditiis nulla hic dolor, in dignissimos.',
    category: 'Calligraphy',
    time: '2 days ago',
  },
  {
    id: 11,
    name: 'Hold My Hand',
    price: 100,
    image: require('../../../assets/images/Products-images/Holdmyhand.jpeg'),
    author: 'Habibi',
    authorpic: require('../../../assets/images/Author-images/HabibiAuth.jpeg'),
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque ipsum rem provident sapiente cum, nemo id quia maiores eum tenetur nostrum. Autem sapiente voluptatibus blanditiis nulla hic dolor, in dignissimos.',
    category: 'Scuplture',
    time: '2 days ago',
  },
  {
    id: 12,
    name: 'Iron Man',
    price: 100,
    image: require('../../../assets/images/Products-images/Ironman.jpeg'),
    author: 'Wowgirl',
    authorpic: require('../../../assets/images/Author-images/WowgirlAuth.jpeg'),
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque ipsum rem provident sapiente cum, nemo id quia maiores eum tenetur nostrum. Autem sapiente voluptatibus blanditiis nulla hic dolor, in dignissimos.',
    category: 'Sketch',
    time: '2 days ago',
  },
  {
    id: 13,
    name: 'Italian Kids',
    price: 100,
    image: require('../../../assets/images/Products-images/Italiankids.jpeg'),
    author: 'Nyd',
    authorpic: require('../../../assets/images/Author-images/me.jpeg'),
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque ipsum rem provident sapiente cum, nemo id quia maiores eum tenetur nostrum. Autem sapiente voluptatibus blanditiis nulla hic dolor, in dignissimos.',
    category: 'Realism',
    time: '2 days ago',
  },
  {
    id: 14,
    name: 'Joker',
    price: 100,
    image: require('../../../assets/images/Products-images/Joker.jpeg'),
    author: 'Wowgirl',
    authorpic: require('../../../assets/images/Author-images/WowgirlAuth.jpeg'),
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque ipsum rem provident sapiente cum, nemo id quia maiores eum tenetur nostrum. Autem sapiente voluptatibus blanditiis nulla hic dolor, in dignissimos.',
    category: 'Sketch',
    time: '2 days ago',
  },
  {
    id: 15,
    name: 'Male Hen',
    price: 100,
    image: require('../../../assets/images/Products-images/MaleHen.jpeg'),
    author: 'Wowgirl',
    authorpic: require('../../../assets/images/Author-images/WowgirlAuth.jpeg'),
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque ipsum rem provident sapiente cum, nemo id quia maiores eum tenetur nostrum. Autem sapiente voluptatibus blanditiis nulla hic dolor, in dignissimos.',
    category: 'Sketch',
    time: '2 days ago',
  },
  {
    id: 16,
    name: 'Paint FACE',
    price: 100,
    image: require('../../../assets/images/Products-images/PAintface.jpeg'),
    author: 'Wowgirl',
    authorpic: require('../../../assets/images/Author-images/WowgirlAuth.jpeg'),
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque ipsum rem provident sapiente cum, nemo id quia maiores eum tenetur nostrum. Autem sapiente voluptatibus blanditiis nulla hic dolor, in dignissimos.',
    category: 'Photography',
    time: '2 days ago',
  },
  {
    id: 17,
    name: 'Ragae Dog',
    price: 100,
    image: require('../../../assets/images/Products-images/Ragedog.jpeg'),
    author: 'Wowgirl',
    authorpic: require('../../../assets/images/Author-images/WowgirlAuth.jpeg'),
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque ipsum rem provident sapiente cum, nemo id quia maiores eum tenetur nostrum. Autem sapiente voluptatibus blanditiis nulla hic dolor, in dignissimos.',
    category: 'Cartoon',
    time: '2 days ago',
  },
  {
    id: 18,
    name: 'Cringe CArtoon',
    price: 100,
    image: require('../../../assets/images/Products-images/reallycringecartoon.jpeg'),
    author: 'Habibi',
    authorpic: require('../../../assets/images/Author-images/HabibiAuth.jpeg'),
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque ipsum rem provident sapiente cum, nemo id quia maiores eum tenetur nostrum. Autem sapiente voluptatibus blanditiis nulla hic dolor, in dignissimos.',
    category: 'Cartoon',
    time: '2 days ago',
  },
  {
    id: 19,
    name: 'Scribble Hulk',
    price: 100,
    image: require('../../../assets/images/Products-images/ScribbleHulk.jpeg'),
    author: 'Wowgirl',
    authorpic: require('../../../assets/images/Author-images/WowgirlAuth.jpeg'),
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque ipsum rem provident sapiente cum, nemo id quia maiores eum tenetur nostrum. Autem sapiente voluptatibus blanditiis nulla hic dolor, in dignissimos.',
    category: 'Pen Art',
    time: '2 days ago',
  },
  {
    id: 20,
    name: 'Smoke',
    price: 100,
    image: require('../../../assets/images/Products-images/Smoke.webp'),
    author: 'Habibi',
    authorpic: require('../../../assets/images/Author-images/HabibiAuth.jpeg'),
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque ipsum rem provident sapiente cum, nemo id quia maiores eum tenetur nostrum. Autem sapiente voluptatibus blanditiis nulla hic dolor, in dignissimos.',
    category: 'Digital Painting',
    time: '2 days ago',
  },
  {
    id: 21,
    name: 'Stairs in the eyes',
    price: 100,
    image: require('../../../assets/images/Products-images/Stairsintheeyes.jpeg'),
    author: 'Habibi',
    authorpic: require('../../../assets/images/Author-images/HabibiAuth.jpeg'),
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque ipsum rem provident sapiente cum, nemo id quia maiores eum tenetur nostrum. Autem sapiente voluptatibus blanditiis nulla hic dolor, in dignissimos.',
    category: 'Pen Art',
    time: '2 days ago',
  },
  {
    id: 22,
    name: 'Alien Spheere',
    price: 100,
    image: require('../../../assets/images/Products-images/Alienshpere.png'),
    author: 'Killian',
    authorpic: require('../../../assets/images/Author-images/killian.jpg'),
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque ipsum rem provident sapiente cum, nemo id quia maiores eum tenetur nostrum. Autem sapiente voluptatibus blanditiis nulla hic dolor, in dignissimos.',
    category: '3D Art',
    time: '2 days ago',
  },
  {
    id: 23,
    name: 'Anneaux',
    price: 100,
    image: require('../../../assets/images/Products-images/anneau.jpg'),
    author: 'Killian',
    authorpic: require('../../../assets/images/Author-images/killian.jpg'),
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque ipsum rem provident sapiente cum, nemo id quia maiores eum tenetur nostrum. Autem sapiente voluptatibus blanditiis nulla hic dolor, in dignissimos.',
    category: '3D Art',
    time: '2 days ago',
  },
];
